bubble:bubble_sort.o buuble1_sort.o
	gcc bubble_sort.o buuble1_sort.o -o bubble
bubble_sort.o:bubble_sort.c
	gcc -c bubble_sort.c
buuble1_sort.o:buuble1_sort.c
	gcc -c buuble1_sort.c
clean:
	rm *.o bubble

