app: string_handling.o mystrlen.o mystring_comp.o mystring_copy.o
	gcc string_handling.o mystrlen.o mystring_comp.o mystring_copy.o -o app

string_handling.o:string_handling.c
		gcc -c string_handling.c

mystrlen.o:mystrlen.c
	gcc -c mystrlen.c

mystring_comp.o:mystring_comp.c
	gcc -c mystring_comp.c

mystring_copy.o:mystring_copy.c
	gcc -c mystring_copy.c
